volumes:
  timescale_data:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: development
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      BACKEND_LOG_LEVEL: ${BACKEND_LOG_LEVEL:-info}
      PG_URL: ${PG_URL}
    volumes:
      - ./backend:/app
      - ./database/migrations:/app/database/migrations
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped
