package assets

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
	"github.com/trakrf/platform/backend/internal/apierrors"
	"github.com/trakrf/platform/backend/internal/middleware"
	"github.com/trakrf/platform/backend/internal/models/asset"
	modelerrors "github.com/trakrf/platform/backend/internal/models/errors"
	"github.com/trakrf/platform/backend/internal/models/shared"
	"github.com/trakrf/platform/backend/internal/services/bulkimport"
	"github.com/trakrf/platform/backend/internal/storage"
	"github.com/trakrf/platform/backend/internal/util/httputil"
)

var validate = func() *validator.Validate {
	v := validator.New()
	v.RegisterTagNameFunc(httputil.JSONTagNameFunc)
	return v
}()

type Handler struct {
	storage           *storage.Storage
	bulkImportService *bulkimport.Service
}

func NewHandler(storage *storage.Storage) *Handler {
	return &Handler{
		storage:           storage,
		bulkImportService: bulkimport.NewService(storage),
	}
}

// resolveLocation reconciles the location_id (canonical) and
// location_external_key (natural-key alternate) inputs on Create/Update.
// Both nil → nil (no location). external_key alone → resolved via lookup.
// Both set → must agree; mismatch returns a validation FieldError.
// Wire field names dropped the `current_` prefix in TRA-580 C-3.
func (handler *Handler) resolveLocation(
	r *http.Request, orgID int, locID *int, locExternalKey *string,
) (*int, *modelerrors.FieldError) {
	hasID := locID != nil
	hasExt := locExternalKey != nil && *locExternalKey != ""

	if !hasID && !hasExt {
		return nil, nil
	}
	if !hasExt {
		return locID, nil
	}

	loc, err := handler.storage.GetLocationByExternalKey(r.Context(), orgID, *locExternalKey)
	if err != nil {
		return nil, &modelerrors.FieldError{
			Field:   "location_external_key",
			Code:    "internal_error",
			Message: err.Error(),
		}
	}
	if loc == nil {
		return nil, &modelerrors.FieldError{
			Field:   "location_external_key",
			Code:    "invalid_value",
			Message: fmt.Sprintf("location_external_key %q not found", *locExternalKey),
		}
	}
	if hasID && *locID != loc.ID {
		return nil, &modelerrors.FieldError{
			Field:   "location_external_key",
			Code:    "invalid_value",
			Message: "location_id and location_external_key disagree",
		}
	}
	return &loc.ID, nil
}

// @Summary      Create an asset
// @Description  Create a new asset record, optionally with one or more tags (RFID, BLE, NFC, barcode).
// @Description
// @Description  The `external_key` field is optional. Provide a value from your system of record
// @Description  (ERP, WMS, asset management) for natural-key joins, or omit it to receive a
// @Description  server-assigned external_key in the format `ASSET-NNNN` (per-organization sequence).
// @Description  A caller-supplied external_key that collides with an existing asset returns 409.
// @Description
// @Description  Returns the created asset with its assigned tags. The Location response header contains the canonical URL.
// @Tags         assets,public
// @ID           assets.create
// @Accept       json
// @Produce      json
// @Param        request  body  asset.CreateAssetWithTagsRequest  true  "Asset to create with optional tags"
// @Success      201  {object}  assets.CreateAssetResponse
// @Header       201  {string}  Location  "Canonical URL of the created resource"
// @Failure      400  {object}  modelerrors.ErrorResponse     "bad_request"
// @Failure      401  {object}  modelerrors.ErrorResponse     "unauthorized"
// @Failure      403  {object}  modelerrors.ErrorResponse     "forbidden"
// @Failure      409  {object}  modelerrors.ErrorResponse     "conflict"
// @Failure      429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Failure      500  {object}  modelerrors.ErrorResponse     "internal_error"
// @Security     APIKey[assets:write]
// @Router       /api/v1/assets [post]
func (handler *Handler) Create(w http.ResponseWriter, r *http.Request) {
	requestID := middleware.GetRequestID(r.Context())

	orgID, err := middleware.GetRequestOrgID(r)
	if err != nil {
		httputil.RespondMissingOrgContext(w, r, requestID)
		return
	}

	var request asset.CreateAssetWithTagsRequest
	if err := httputil.DecodeJSONStrict(r, &request); err != nil {
		httputil.RespondDecodeError(w, r, err, requestID)
		return
	}

	// Apply API-consumer defaults for fields the UI always sends explicitly
	// but API consumers commonly omit. Absence is distinguishable from zero
	// because these fields are pointer-typed.
	if request.IsActive == nil {
		t := true
		request.IsActive = &t
	}
	if request.ValidFrom == nil || request.ValidFrom.IsZero() {
		fd := shared.FlexibleDate{Time: time.Now().UTC()}
		request.ValidFrom = &fd
	}

	// TRA-514: external_key is optional ("" → server autogens ASSET-NNNN), but
	// whitespace-only is ambiguous — surface the bad input instead of silently
	// substituting an autogenerated value.
	if request.ExternalKey != "" && strings.TrimSpace(request.ExternalKey) == "" {
		msg := "external_key must contain non-whitespace characters"
		httputil.WriteJSONErrorWithFields(w, r, http.StatusBadRequest, modelerrors.ErrValidation,
			msg, requestID,
			[]modelerrors.FieldError{{
				Field:   "external_key",
				Code:    "invalid_value",
				Message: msg,
			}})

		return
	}

	if err := validate.Struct(request); err != nil {
		httputil.RespondValidationError(w, r, err, requestID)
		return
	}

	resolved, fErr := handler.resolveLocation(r, orgID, request.LocationID, request.LocationExternalKey)
	if fErr != nil {
		if fErr.Code == "internal_error" {
			httputil.WriteJSONError(w, r, http.StatusInternalServerError, modelerrors.ErrInternal,
				fErr.Message, requestID)

			return
		}
		httputil.WriteJSONErrorWithFields(w, r, http.StatusBadRequest, modelerrors.ErrValidation,
			fErr.Message, requestID,
			[]modelerrors.FieldError{*fErr})

		return
	}
	request.LocationID = resolved

	request.OrgID = orgID

	result, err := handler.storage.CreateAssetWithTags(r.Context(), request)
	if err != nil {
		if strings.Contains(err.Error(), "already exist") {
			httputil.WriteJSONError(w, r, http.StatusConflict, modelerrors.ErrConflict,
				err.Error(), requestID)

			return
		}
		httputil.RespondStorageError(w, r, err, requestID)
		return
	}

	w.Header().Set("Location", "/api/v1/assets/"+strconv.Itoa(result.ID))
	httputil.WriteJSON(w, http.StatusCreated, map[string]any{"data": asset.ToPublicAssetView(*result)})
}

// @Summary      Update an asset
// @Description  Update mutable fields on an existing asset. Only fields included in the request body are changed.
// @Tags         assets,public
// @ID           assets.update
// @Accept       json
// @Produce      json
// @Param        id       path  int                       true  "Asset id (canonical)"
// @Param        request  body  asset.UpdateAssetRequest  true  "Fields to update"
// @Success      200  {object}  assets.UpdateAssetResponse
// @Failure      400  {object}  modelerrors.ErrorResponse     "bad_request"
// @Failure      401  {object}  modelerrors.ErrorResponse     "unauthorized"
// @Failure      403  {object}  modelerrors.ErrorResponse     "forbidden"
// @Failure      404  {object}  modelerrors.ErrorResponse     "not_found"
// @Failure      409  {object}  modelerrors.ErrorResponse     "conflict"
// @Failure      429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Failure      500  {object}  modelerrors.ErrorResponse     "internal_error"
// @Security     APIKey[assets:write]
// @Router       /api/v1/assets/{id} [put]
func (handler *Handler) Update(w http.ResponseWriter, req *http.Request) {
	reqID := middleware.GetRequestID(req.Context())

	orgID, err := middleware.GetRequestOrgID(req)
	if err != nil {
		httputil.RespondMissingOrgContext(w, req, reqID)
		return
	}

	id, ok := handler.parseAndVerifyAssetID(w, req, orgID, reqID)
	if !ok {
		return
	}

	handler.doUpdate(w, req, orgID, id)
}

func (handler *Handler) doUpdate(w http.ResponseWriter, req *http.Request, orgID, id int) {
	reqID := middleware.GetRequestID(req.Context())

	var request asset.UpdateAssetRequest
	explicitNulls, err := httputil.DecodeJSONStrictWithNulls(req, &request)
	if err != nil {
		httputil.RespondDecodeError(w, req, err, reqID)
		return
	}

	// valid_from is NOT NULL in the DB; explicit null is invalid. Explicit
	// valid_to null requests a clear (SQL NULL), per TRA-468 wire convention.
	if _, ok := explicitNulls["valid_from"]; ok {
		httputil.WriteJSONErrorWithFields(w, req, http.StatusBadRequest, modelerrors.ErrValidation,
			"validation failed", reqID,
			[]modelerrors.FieldError{{
				Field:   "valid_from",
				Code:    "invalid_value",
				Message: "valid_from cannot be null; omit the field to leave unchanged, or provide a date",
			}})

		return
	}
	if _, ok := explicitNulls["valid_to"]; ok {
		request.ClearValidTo = true
	}

	if err := validate.Struct(request); err != nil {
		httputil.RespondValidationError(w, req, err, reqID)
		return
	}

	resolved, fErr := handler.resolveLocation(req, orgID, request.LocationID, request.LocationExternalKey)
	if fErr != nil {
		if fErr.Code == "internal_error" {
			httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
				fErr.Message, reqID)

			return
		}
		httputil.WriteJSONErrorWithFields(w, req, http.StatusBadRequest, modelerrors.ErrValidation,
			fErr.Message, reqID,
			[]modelerrors.FieldError{*fErr})

		return
	}
	request.LocationID = resolved

	result, err := handler.storage.UpdateAsset(req.Context(), orgID, id, request)
	if err != nil {
		if strings.Contains(err.Error(), "already exist") {
			httputil.WriteJSONError(w, req, http.StatusConflict, modelerrors.ErrConflict,
				err.Error(), reqID)

			return
		}
		httputil.RespondStorageError(w, req, err, reqID)
		return
	}

	if result == nil {
		httputil.Respond404(w, req, apierrors.AssetNotFound, reqID)
		return
	}

	httputil.WriteJSON(w, http.StatusOK, map[string]any{"data": asset.ToPublicAssetView(*result)})
}

// @Summary      Delete an asset
// @Description  Delete an asset by its canonical id. The asset is removed from all subsequent queries and its external_key becomes immediately available for reuse. Returns 204 on success, 404 if the asset does not exist or has already been deleted.
// @Tags         assets,public
// @ID           assets.delete
// @Accept       json
// @Produce      json
// @Param        id  path  int  true  "Asset id (canonical)"
// @Success      204  "deleted"
// @Failure      401  {object}  modelerrors.ErrorResponse     "unauthorized"
// @Failure      403  {object}  modelerrors.ErrorResponse     "forbidden"
// @Failure      404  {object}  modelerrors.ErrorResponse     "not_found"
// @Failure      429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Failure      500  {object}  modelerrors.ErrorResponse     "internal_error"
// @Security     APIKey[assets:write]
// @Router       /api/v1/assets/{id} [delete]
func (handler *Handler) Delete(w http.ResponseWriter, req *http.Request) {
	reqID := middleware.GetRequestID(req.Context())

	orgID, err := middleware.GetRequestOrgID(req)
	if err != nil {
		httputil.RespondMissingOrgContext(w, req, reqID)
		return
	}

	id, ok := handler.parseAndVerifyAssetID(w, req, orgID, reqID)
	if !ok {
		return
	}

	handler.doDelete(w, req, orgID, id)
}

func (handler *Handler) doDelete(w http.ResponseWriter, req *http.Request, orgID, id int) {
	reqID := middleware.GetRequestID(req.Context())

	deleted, err := handler.storage.DeleteAsset(req.Context(), orgID, id)
	if err != nil {
		httputil.RespondStorageError(w, req, err, reqID)
		return
	}

	if !deleted {
		httputil.Respond404(w, req, apierrors.AssetNotFound, reqID)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}

// ListAssetsResponse is the typed envelope returned by GET /api/v1/assets.
type ListAssetsResponse struct {
	Data       []asset.PublicAssetView `json:"data"`
	Limit      int                     `json:"limit"       example:"50"`
	Offset     int                     `json:"offset"      example:"0"`
	TotalCount int                     `json:"total_count" example:"100"`
}

// GetAssetResponse is the typed envelope returned by GET /api/v1/assets/{id}.
type GetAssetResponse struct {
	Data asset.PublicAssetView `json:"data"`
}

// CreateAssetResponse is the typed envelope returned by POST /api/v1/assets.
type CreateAssetResponse struct {
	Data asset.PublicAssetView `json:"data"`
}

// UpdateAssetResponse is the typed envelope returned by PUT /api/v1/assets/{id}.
type UpdateAssetResponse struct {
	Data asset.PublicAssetView `json:"data"`
}

// @Summary List assets
// @Description Paginated assets list with natural-key filters, sort, and substring search
// @Tags assets,public
// @ID assets.list
// @Accept json
// @Produce json
// @Param limit                 query int    false "max 200"   default(50)
// @Param offset                query int    false "min 0"     default(0)
// @Param location_id           query int    false "filter by current location id (canonical, may repeat)"
// @Param location_external_key query string false "filter by current location external_key (may repeat)"
// @Param is_active             query bool   false "filter by active flag"
// @Param q                     query string false "substring search (case-insensitive) on name, external_key, description, and active tag values"
// @Param sort                  query []string false "comma-separated; prefix '-' for DESC" collectionFormat(csv) Enums(external_key, -external_key, name, -name, created_at, -created_at, updated_at, -updated_at)
// @Success 200 {object} assets.ListAssetsResponse
// @Header  200 {integer} X-RateLimit-Limit     "Steady-state requests/min for this API key"
// @Header  200 {integer} X-RateLimit-Remaining "Requests remaining before throttling; bounded by X-RateLimit-Limit"
// @Header  200 {integer} X-RateLimit-Reset     "Unix timestamp (seconds) when X-RateLimit-Remaining will next equal X-RateLimit-Limit"
// @Failure 400 {object} modelerrors.ErrorResponse
// @Failure 401 {object} modelerrors.ErrorResponse
// @Failure 403 {object} modelerrors.ErrorResponse
// @Failure 429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Header  429 {integer} Retry-After           "Seconds to wait before retrying"
// @Failure 500 {object} modelerrors.ErrorResponse
// @Security APIKey[assets:read]
// @Router /api/v1/assets [get]
func (handler *Handler) ListAssets(w http.ResponseWriter, req *http.Request) {
	reqID := middleware.GetRequestID(req.Context())

	orgID, err := middleware.GetRequestOrgID(req)
	if err != nil {
		httputil.RespondMissingOrgContext(w, req, reqID)
		return
	}

	params, err := httputil.ParseListParams(req, httputil.ListAllowlist{
		Filters:     []string{"location_id", "location_external_key", "is_active", "q"},
		BoolFilters: []string{"is_active"},
		Sorts:       []string{"external_key", "name", "created_at", "updated_at"},
	})
	if err != nil {
		httputil.RespondListParamError(w, req, err, reqID)
		return
	}

	f := asset.ListFilter{
		LocationExternalKeys: params.Filters["location_external_key"],
		Limit:                params.Limit,
		Offset:               params.Offset,
	}
	if vs, ok := params.Filters["location_id"]; ok && len(vs) > 0 {
		f.LocationIDs = make([]int, 0, len(vs))
		for _, s := range vs {
			n, err := strconv.Atoi(s)
			if err != nil || n < 1 {
				httputil.WriteJSONErrorWithFields(w, req, http.StatusBadRequest, modelerrors.ErrValidation,
					"invalid location_id", reqID,
					[]modelerrors.FieldError{{
						Field:   "location_id",
						Code:    "invalid_value",
						Message: fmt.Sprintf("location_id %q must be a positive integer", s),
					}})

				return
			}
			f.LocationIDs = append(f.LocationIDs, n)
		}
	}
	if vs, ok := params.Filters["is_active"]; ok && len(vs) > 0 {
		b := vs[0] == "true"
		f.IsActive = &b
	}
	if vs, ok := params.Filters["q"]; ok && len(vs) > 0 {
		f.Q = &vs[0]
	}
	for _, s := range params.Sorts {
		f.Sorts = append(f.Sorts, asset.ListSort{Field: s.Field, Desc: s.Desc})
	}

	items, err := handler.storage.ListAssetsFiltered(req.Context(), orgID, f)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), reqID)

		return
	}

	total, err := handler.storage.CountAssetsFiltered(req.Context(), orgID, f)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), reqID)

		return
	}

	out := make([]asset.PublicAssetView, 0, len(items))
	for _, a := range items {
		out = append(out, asset.ToPublicAssetView(a))
	}

	httputil.WriteJSON(w, http.StatusOK, ListAssetsResponse{
		Data:       out,
		Limit:      params.Limit,
		Offset:     params.Offset,
		TotalCount: total,
	})
}

// @Summary Get asset by canonical id
// @Description Retrieve an asset by its canonical id. Returns 404 if the asset does not exist.
// @Tags assets,public
// @ID assets.get
// @Param id path int true "Asset id (canonical)"
// @Success 200 {object} assets.GetAssetResponse
// @Header  200 {integer} X-RateLimit-Limit     "Steady-state requests/min for this API key"
// @Header  200 {integer} X-RateLimit-Remaining "Requests remaining before throttling; bounded by X-RateLimit-Limit"
// @Header  200 {integer} X-RateLimit-Reset     "Unix timestamp (seconds) when X-RateLimit-Remaining will next equal X-RateLimit-Limit"
// @Failure 400 {object} modelerrors.ErrorResponse
// @Failure 401 {object} modelerrors.ErrorResponse
// @Failure 403 {object} modelerrors.ErrorResponse
// @Failure 404 {object} modelerrors.ErrorResponse
// @Failure 429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Header  429 {integer} Retry-After           "Seconds to wait before retrying"
// @Security APIKey[assets:read]
// @Router /api/v1/assets/{id} [get]
func (handler *Handler) GetAsset(w http.ResponseWriter, req *http.Request) {
	reqID := middleware.GetRequestID(req.Context())

	orgID, err := middleware.GetRequestOrgID(req)
	if err != nil {
		httputil.RespondMissingOrgContext(w, req, reqID)
		return
	}

	idParam := chi.URLParam(req, "id")
	id, err := httputil.ParseSurrogateID(idParam)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusBadRequest, modelerrors.ErrBadRequest,
			err.Error(), reqID)

		return
	}

	view, err := handler.storage.GetAssetWithLocationByIDForTest(req.Context(), orgID, id)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), reqID)

		return
	}
	if view == nil {
		httputil.Respond404(w, req, apierrors.AssetNotFound, reqID)
		return
	}

	httputil.WriteJSON(w, http.StatusOK, map[string]any{
		"data": asset.ToPublicAssetView(*view),
	})
}

// @Summary Look up an asset by external_key
// @Description Find a single live asset by its external_key. Equality match only.
// @Description Returns the matching object (200) or 404. Multiple natural-key parameters or none returns 400.
// @Description Soft-deleted rows are not addressable through this endpoint.
// @Tags assets,public
// @ID assets.lookup
// @Param external_key query string true "Asset external_key (natural key)"
// @Success 200 {object} assets.GetAssetResponse
// @Header  200 {integer} X-RateLimit-Limit     "Steady-state requests/min for this API key"
// @Header  200 {integer} X-RateLimit-Remaining "Requests remaining before throttling; bounded by X-RateLimit-Limit"
// @Header  200 {integer} X-RateLimit-Reset     "Unix timestamp (seconds) when X-RateLimit-Remaining will next equal X-RateLimit-Limit"
// @Failure 400 {object} modelerrors.ErrorResponse "bad_request"
// @Failure 401 {object} modelerrors.ErrorResponse "unauthorized"
// @Failure 403 {object} modelerrors.ErrorResponse "forbidden"
// @Failure 404 {object} modelerrors.ErrorResponse "not_found"
// @Failure 429 {object} modelerrors.ErrorResponse "rate_limited"
// @Header  429 {integer} Retry-After           "Seconds to wait before retrying"
// @Security APIKey[assets:read]
// @Router /api/v1/assets/lookup [get]
func (handler *Handler) Lookup(w http.ResponseWriter, req *http.Request) {
	reqID := middleware.GetRequestID(req.Context())

	orgID, err := middleware.GetRequestOrgID(req)
	if err != nil {
		httputil.RespondMissingOrgContext(w, req, reqID)
		return
	}

	q := req.URL.Query()
	// D-4: duplicate external_key params silently first-wins is an LLM-hostile
	// bug; reject them explicitly. Repeated values (same or different) → 400.
	if len(q["external_key"]) > 1 {
		httputil.WriteJSONError(w, req, http.StatusBadRequest, modelerrors.ErrBadRequest,
			"exactly one of: external_key", reqID)
		return
	}

	naturalKeyParams := []string{"external_key"}
	provided := 0
	for _, k := range naturalKeyParams {
		if q.Has(k) && q.Get(k) != "" {
			provided++
		}
	}

	if provided == 0 {
		httputil.WriteJSONError(w, req, http.StatusBadRequest, modelerrors.ErrBadRequest,
			"exactly one of: external_key", reqID)

		return
	}
	if provided > 1 {
		httputil.WriteJSONError(w, req, http.StatusBadRequest, modelerrors.ErrBadRequest,
			"exactly one of: external_key", reqID)

		return
	}

	externalKey := q.Get("external_key")
	a, err := handler.storage.GetAssetByExternalKey(req.Context(), orgID, externalKey)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), reqID)

		return
	}
	if a == nil {
		httputil.Respond404(w, req, apierrors.AssetNotFound, reqID)
		return
	}

	httputil.WriteJSON(w, http.StatusOK, map[string]any{
		"data": asset.ToPublicAssetView(*a),
	})
}

// AddTagResponse is the typed envelope returned by POST /api/v1/assets/{id}/tags.
type AddTagResponse struct {
	Data shared.Tag `json:"data"`
}

// @Summary      Add a tag to an asset
// @Description  Attach a tag (RFID EPC, BLE beacon ID, barcode, etc.) to an existing asset.
// @Description  The tag must be unique within the organization.
// @Tags         assets,public
// @ID           assets.tags.add
// @Accept       json
// @Produce      json
// @Param        id       path  int                true  "Asset id (canonical)"
// @Param        request  body  shared.TagRequest  true  "Tag to attach"
// @Success      201  {object}  assets.AddTagResponse         "tag attached"
// @Failure      400  {object}  modelerrors.ErrorResponse     "bad_request"
// @Failure      401  {object}  modelerrors.ErrorResponse     "unauthorized"
// @Failure      403  {object}  modelerrors.ErrorResponse     "forbidden"
// @Failure      404  {object}  modelerrors.ErrorResponse     "not_found"
// @Failure      429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Failure      500  {object}  modelerrors.ErrorResponse     "internal_error"
// @Security     APIKey[assets:write]
// @Router       /api/v1/assets/{id}/tags [post]
func (handler *Handler) AddTag(w http.ResponseWriter, r *http.Request) {
	requestID := middleware.GetRequestID(r.Context())

	orgID, err := middleware.GetRequestOrgID(r)
	if err != nil {
		httputil.RespondMissingOrgContext(w, r, requestID)
		return
	}

	id, ok := handler.parseAndVerifyAssetID(w, r, orgID, requestID)
	if !ok {
		return
	}

	handler.doAddAssetTag(w, r, orgID, id)
}

// doAddAssetTag decodes the tag body, validates it, and inserts via storage.
// Caller must have already verified that (orgID, assetID) names a real asset
// — storage.AddTagToAsset does NOT cross-check ownership before INSERT, so
// skipping the pre-check would allow cross-org tag attachment.
func (handler *Handler) doAddAssetTag(w http.ResponseWriter, r *http.Request, orgID, assetID int) {
	requestID := middleware.GetRequestID(r.Context())

	var request shared.TagRequest
	if err := httputil.DecodeJSON(r, &request); err != nil {
		httputil.RespondDecodeError(w, r, err, requestID)
		return
	}

	if err := validate.Struct(request); err != nil {
		httputil.RespondValidationError(w, r, err, requestID)
		return
	}

	tag, err := handler.storage.AddTagToAsset(r.Context(), orgID, assetID, request)
	if err != nil {
		if strings.Contains(err.Error(), "already exist") {
			httputil.WriteJSONError(w, r, http.StatusConflict, modelerrors.ErrConflict,
				err.Error(), requestID)

			return
		}
		httputil.RespondStorageError(w, r, err, requestID)
		return
	}

	httputil.WriteJSON(w, http.StatusCreated, AddTagResponse{Data: *tag})
}

// @Summary      Remove a tag from an asset
// @Description  Detach a tag from an asset by its tag record id.
// @Tags         assets,public
// @ID           assets.tags.remove
// @Accept       json
// @Produce      json
// @Param        asset_id  path  int  true  "Asset id (canonical)"
// @Param        tag_id    path  int  true  "Tag id"
// @Success      204  "deleted"
// @Failure      400  {object}  modelerrors.ErrorResponse     "bad_request"
// @Failure      401  {object}  modelerrors.ErrorResponse     "unauthorized"
// @Failure      403  {object}  modelerrors.ErrorResponse     "forbidden"
// @Failure      404  {object}  modelerrors.ErrorResponse     "not_found"
// @Failure      429  {object}  modelerrors.ErrorResponse     "rate_limited"
// @Failure      500  {object}  modelerrors.ErrorResponse     "internal_error"
// @Security     APIKey[assets:write]
// @Router       /api/v1/assets/{asset_id}/tags/{tag_id} [delete]
func (handler *Handler) RemoveTag(w http.ResponseWriter, r *http.Request) {
	requestID := middleware.GetRequestID(r.Context())

	orgID, err := middleware.GetRequestOrgID(r)
	if err != nil {
		httputil.RespondMissingOrgContext(w, r, requestID)
		return
	}

	idParam := chi.URLParam(r, "asset_id")
	id, err := httputil.ParseSurrogateID(idParam)
	if err != nil {
		httputil.WriteJSONError(w, r, http.StatusBadRequest, modelerrors.ErrBadRequest,
			err.Error(), requestID)

		return
	}

	a, err := handler.storage.GetAssetByID(r.Context(), orgID, &id)
	if err != nil {
		httputil.WriteJSONError(w, r, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), requestID)

		return
	}
	if a == nil || a.OrgID != orgID {
		httputil.Respond404(w, r, apierrors.AssetNotFound, requestID)
		return
	}

	handler.doRemoveAssetTag(w, r, orgID, a.ID)
}

// doRemoveAssetTag parses {tag_id} and soft-deletes via storage.
// Storage guards cross-asset / cross-org misuse itself (EXISTS subquery on
// asset_id + org_id), so a missing match surfaces as deleted=false rather
// than an error.
func (handler *Handler) doRemoveAssetTag(w http.ResponseWriter, r *http.Request, orgID, assetID int) {
	requestID := middleware.GetRequestID(r.Context())

	tagIDParam := chi.URLParam(r, "tag_id")
	tagID, err := strconv.Atoi(tagIDParam)
	if err != nil {
		httputil.WriteJSONError(w, r, http.StatusBadRequest, modelerrors.ErrBadRequest,
			err.Error(), requestID)

		return
	}

	_, err = handler.storage.RemoveAssetTag(r.Context(), orgID, assetID, tagID)
	if err != nil {
		httputil.RespondStorageError(w, r, err, requestID)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}

// parseAndVerifyAssetID extracts {id}, parses it as a surrogate int, and
// verifies the asset exists and belongs to the caller's org. Writes an
// appropriate 400 / 404 / 500 response and returns ok=false on any failure.
func (handler *Handler) parseAndVerifyAssetID(w http.ResponseWriter, req *http.Request, orgID int, reqID string) (int, bool) {
	idParam := chi.URLParam(req, "id")
	id, err := httputil.ParseSurrogateID(idParam)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusBadRequest, modelerrors.ErrBadRequest,
			err.Error(), reqID)

		return 0, false
	}

	a, err := handler.storage.GetAssetByID(req.Context(), orgID, &id)
	if err != nil {
		httputil.WriteJSONError(w, req, http.StatusInternalServerError, modelerrors.ErrInternal,
			err.Error(), reqID)

		return 0, false
	}
	if a == nil || a.OrgID != orgID {
		httputil.Respond404(w, req, apierrors.AssetNotFound, reqID)
		return 0, false
	}

	return a.ID, true
}

// RegisterRoutes keeps only session-only surface (bulk CSV). Public read,
// write, and lookup routes are registered directly in
// internal/cmd/serve/router.go under EitherAuth.
func (handler *Handler) RegisterRoutes(r chi.Router) {
	r.Post("/api/v1/assets/bulk", handler.UploadCSV)
	r.Get("/api/v1/assets/bulk/{jobId}", handler.GetJobStatus)
}
