SET search_path=trakrf,public;

-- TRA-482: replace UNIQUE(org_id, type, value, valid_from) with a partial
-- unique index on live rows only. The legacy 4-column constraint never
-- fired in practice because every insert uses DEFAULT CURRENT_TIMESTAMP,
-- making every row unique by timestamp. Same pattern as TRA-475 applied
-- to assets and locations.

-- Step 1: dedup existing live duplicates, keeping the most-recently-updated
-- row per (org_id, type, value). Tie-break by id DESC so the result is
-- deterministic. Idempotent: zero updates if no duplicates exist.
WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY org_id, type, value
               ORDER BY updated_at DESC, id DESC
           ) AS rn
      FROM trakrf.identifiers
     WHERE deleted_at IS NULL
)
UPDATE trakrf.identifiers i
   SET deleted_at = now()
  FROM ranked r
 WHERE i.id = r.id
   AND r.rn > 1;

-- Step 2: drop the legacy 4-column unique constraint. The constraint name
-- is auto-generated by Postgres from the column list.
ALTER TABLE trakrf.identifiers
    DROP CONSTRAINT identifiers_org_id_type_value_valid_from_key;

-- Step 3: install the partial unique index covering live rows only.
-- A re-create of the same identifier value after soft-delete is intentionally
-- allowed (and tested) — soft-delete is a tombstone, not a permanent block.
-- This also means a single (org_id, type, value) is live on at most ONE
-- attachment (asset OR location) at a time across the whole org — correct
-- for physical RFID/BLE tags.
CREATE UNIQUE INDEX identifiers_org_id_type_value_unique
    ON trakrf.identifiers (org_id, type, value)
    WHERE deleted_at IS NULL;
