SET search_path=trakrf,public;

DROP FUNCTION IF EXISTS create_asset_with_identifiers(
    INT, VARCHAR, VARCHAR, VARCHAR, TEXT, INT, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN, JSONB, JSONB
);

DROP FUNCTION IF EXISTS create_location_with_identifiers(
    INT, VARCHAR, VARCHAR, TEXT, INT, TIMESTAMPTZ, TIMESTAMPTZ, BOOLEAN, JSONB, JSONB
);
