SET search_path=trakrf,public;

-- TRA-475: replace UNIQUE(org_id, identifier, valid_from) with a partial
-- unique index on live rows only. The legacy 3-column constraint never
-- fired in practice because handlers set valid_from = now() per insert,
-- making every row unique by timestamp.

-- Step 1: dedup existing live duplicates, keeping the most-recently-updated
-- row per (org_id, identifier). Tie-break by id DESC so the result is
-- deterministic. Idempotent: zero updates if no duplicates exist.
WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY org_id, identifier
               ORDER BY updated_at DESC, id DESC
           ) AS rn
      FROM trakrf.assets
     WHERE deleted_at IS NULL
)
UPDATE trakrf.assets a
   SET deleted_at = now()
  FROM ranked r
 WHERE a.id = r.id
   AND r.rn > 1;

WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY org_id, identifier
               ORDER BY updated_at DESC, id DESC
           ) AS rn
      FROM trakrf.locations
     WHERE deleted_at IS NULL
)
UPDATE trakrf.locations l
   SET deleted_at = now()
  FROM ranked r
 WHERE l.id = r.id
   AND r.rn > 1;

-- Step 2: drop the legacy 3-column unique constraint on both tables.
-- The constraint name is auto-generated by Postgres from the column list.
ALTER TABLE trakrf.assets
    DROP CONSTRAINT assets_org_id_identifier_valid_from_key;

ALTER TABLE trakrf.locations
    DROP CONSTRAINT locations_org_id_identifier_valid_from_key;

-- Step 3: install partial unique indexes covering live rows only.
-- A re-create of the same identifier after soft-delete is intentionally
-- allowed (and tested) — soft-delete is a tombstone, not a permanent block.
CREATE UNIQUE INDEX assets_org_id_identifier_unique
    ON trakrf.assets (org_id, identifier)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX locations_org_id_identifier_unique
    ON trakrf.locations (org_id, identifier)
    WHERE deleted_at IS NULL;
