package storage

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/trakrf/platform/backend/internal/models/webhook"
)

// ErrWebhookExists is returned when a create would violate the one-live-
// webhook-per-org invariant (idx_webhooks_one_per_org). Handlers map it to 409.
var ErrWebhookExists = errors.New("webhook already exists for this organization")

// webhookColumns is the canonical SELECT/RETURNING list, kept identical across
// every webhooks query so scan targets line up.
const webhookColumns = `id, org_id, url, secret, enabled, created_at, updated_at, deleted_at`

func scanWebhook(row pgx.Row, w *webhook.Webhook) error {
	return row.Scan(&w.ID, &w.OrgID, &w.URL, &w.Secret, &w.Enabled, &w.CreatedAt, &w.UpdatedAt, &w.DeletedAt)
}

// CreateWebhook inserts the org's webhook. The secret is generated by the
// caller (handlers/webhooks) so the cleartext can be returned exactly once.
// Returns ErrWebhookExists when the org already has a live webhook.
func (s *Storage) CreateWebhook(ctx context.Context, orgID int, url, secret string, enabled bool) (*webhook.Webhook, error) {
	query := `INSERT INTO trakrf.webhooks (org_id, url, secret, enabled)
		VALUES ($1, $2, $3, $4)
		RETURNING ` + webhookColumns

	var w webhook.Webhook
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		return scanWebhook(tx.QueryRow(ctx, query, orgID, url, secret, enabled), &w)
	})
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" && pgErr.ConstraintName == "idx_webhooks_one_per_org" {
			return nil, ErrWebhookExists
		}
		return nil, fmt.Errorf("failed to create webhook: %w", err)
	}
	return &w, nil
}

// GetWebhook returns the org's live webhook, or (nil, nil) when it has none.
func (s *Storage) GetWebhook(ctx context.Context, orgID int) (*webhook.Webhook, error) {
	query := `SELECT ` + webhookColumns + `
		FROM trakrf.webhooks
		WHERE org_id = $1 AND deleted_at IS NULL`

	var w webhook.Webhook
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		return scanWebhook(tx.QueryRow(ctx, query, orgID), &w)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get webhook: %w", err)
	}
	return &w, nil
}

// GetWebhookByID returns the org's live webhook by id, or (nil, nil) when the
// id names no live row of this org.
func (s *Storage) GetWebhookByID(ctx context.Context, orgID, id int) (*webhook.Webhook, error) {
	query := `SELECT ` + webhookColumns + `
		FROM trakrf.webhooks
		WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL`

	var w webhook.Webhook
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		return scanWebhook(tx.QueryRow(ctx, query, id, orgID), &w)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get webhook: %w", err)
	}
	return &w, nil
}

// UpdateWebhook applies a partial update. Absent (nil) fields are left as-is.
// Returns (nil, nil) when the id names no live row of this org.
func (s *Storage) UpdateWebhook(ctx context.Context, orgID, id int, req webhook.UpdateRequest) (*webhook.Webhook, error) {
	query := `UPDATE trakrf.webhooks
		SET url = COALESCE($3, url),
		    enabled = COALESCE($4, enabled)
		WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
		RETURNING ` + webhookColumns

	var w webhook.Webhook
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		return scanWebhook(tx.QueryRow(ctx, query, id, orgID, req.URL, req.Enabled), &w)
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to update webhook: %w", err)
	}
	return &w, nil
}

// DeleteWebhook soft-deletes the org's webhook. Reports whether a row was
// deleted. The one-per-org index is partial on deleted_at IS NULL, so the org
// can register a new webhook immediately afterwards.
func (s *Storage) DeleteWebhook(ctx context.Context, orgID, id int) (bool, error) {
	query := `UPDATE trakrf.webhooks
		SET deleted_at = CURRENT_TIMESTAMP
		WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL`

	var affected int64
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		ct, err := tx.Exec(ctx, query, id, orgID)
		if err != nil {
			return err
		}
		affected = ct.RowsAffected()
		return nil
	})
	if err != nil {
		return false, fmt.Errorf("failed to delete webhook: %w", err)
	}
	return affected > 0, nil
}

// GetWebhookForDelivery resolves the org's webhook AND its entitlement in one
// round trip, for the dispatcher's send path (TRA-1043).
//
// Entitlement matters here because webhook *delivery* is not an inbound HTTP
// request, so no middleware touches it: without this check an org that
// registered a webhook during a trial and never converted would keep receiving
// events indefinitely. The caller skips (and counts) rather than queueing —
// buffering a lapsed window would dump a flood of stale events describing a
// world that has moved on, the same reasoning as QoS0 fire-and-forget ingestion.
//
// Returns (nil, entitled, nil) when the org has no webhook. The caller
// distinguishes disabled from unentitled from absent for its metrics.
func (s *Storage) GetWebhookForDelivery(ctx context.Context, orgID int) (*webhook.Webhook, bool, error) {
	query := `SELECT ` + webhookColumns + `, trakrf.org_is_entitled($1) AS entitled
		FROM trakrf.webhooks
		WHERE org_id = $1 AND deleted_at IS NULL`

	var w webhook.Webhook
	var entitled bool
	found := true
	err := s.WithOrgTx(ctx, orgID, func(tx pgx.Tx) error {
		err := tx.QueryRow(ctx, query, orgID).Scan(&w.ID, &w.OrgID, &w.URL, &w.Secret, &w.Enabled,
			&w.CreatedAt, &w.UpdatedAt, &w.DeletedAt, &entitled)
		if errors.Is(err, pgx.ErrNoRows) {
			found = false
			// The org has no webhook; entitlement is irrelevant to the caller's
			// decision, so a second query for it would be wasted.
			return nil
		}
		return err
	})
	if err != nil {
		return nil, false, fmt.Errorf("failed to resolve webhook for delivery: %w", err)
	}
	if !found {
		return nil, false, nil
	}
	return &w, entitled, nil
}
