-- TRA-810 — pull live organizations from Cloud source.
-- Natural key: identifier. Surrogate id regenerated by trigger.
\set ON_ERROR_STOP on

INSERT INTO trakrf.organizations
    (name, identifier, metadata, valid_from, valid_to, is_active,
     created_at, updated_at)
SELECT
    name, identifier, metadata, valid_from, valid_to, is_active,
    created_at, updated_at
FROM cloud_src.organizations
WHERE deleted_at IS NULL;

DO $$
DECLARE src_n INT; tgt_n INT;
BEGIN
    SELECT count(*) INTO src_n FROM cloud_src.organizations WHERE deleted_at IS NULL;
    SELECT count(*) INTO tgt_n FROM trakrf.organizations;
    IF src_n <> tgt_n THEN
        RAISE EXCEPTION 'organizations count mismatch: src=% tgt=%', src_n, tgt_n;
    END IF;
    RAISE NOTICE 'organizations OK: % rows', tgt_n;
END $$;
