// Package swaggerspec embeds the internal OpenAPI 3.0 spec generated by
// the apispec tool and serves it over HTTP for the internal Swagger UI.
// The spec is regenerated on every build; see just backend api-spec.
package swaggerspec

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.internal.json
var internalJSON []byte

//go:embed openapi.internal.yaml
var internalYAML []byte

// ServeJSON writes the embedded internal OpenAPI spec as JSON.
func ServeJSON(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(internalJSON)
}

// ServeYAML writes the embedded internal OpenAPI spec as YAML.
func ServeYAML(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/yaml")
	_, _ = w.Write(internalYAML)
}
