// Package swaggerspec embeds the OpenAPI 3.0 specs generated by the apispec
// tool and serves them over HTTP. Two specs live here:
//   - openapi.internal.{json,yaml}: full surface including session-only routes,
//     used by the internal Swagger UI.
//   - openapi.public.{json,yaml}: the API-key-authenticated public surface,
//     served at /api/v1/openapi.{json,yaml} for integrators and codegen tools.
//
// Both specs are regenerated on every build; see just backend api-spec.
package swaggerspec

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.internal.json
var internalJSON []byte

//go:embed openapi.internal.yaml
var internalYAML []byte

//go:embed openapi.public.json
var publicJSON []byte

//go:embed openapi.public.yaml
var publicYAML []byte

// ServeJSON writes the embedded internal OpenAPI spec as JSON.
func ServeJSON(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(internalJSON)
}

// ServeYAML writes the embedded internal OpenAPI spec as YAML.
func ServeYAML(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/yaml")
	_, _ = w.Write(internalYAML)
}

// ServePublicJSON writes the embedded public OpenAPI spec as JSON.
func ServePublicJSON(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(publicJSON)
}

// ServePublicYAML writes the embedded public OpenAPI spec as YAML.
func ServePublicYAML(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/yaml")
	_, _ = w.Write(publicYAML)
}
